# Protocol for the Activity ladder. (tier, anchor_id, opener, done, test, drop_id, say)
#
# Activity is where the two-minute rule earns its keep. "Spend a month doing twenty minutes a
# day on one skill" is not refusable at the level of the month; it is refusable every single
# evening, so the opener names the evening act, not the month.
ROWS = [
(1,"teeth","Pick the brush up with the wrong hand before you think about it.","your teeth are clean and the other hand never took over.","to make a mess of it and give up halfway through.","check"),
(2,"plate","Put your plate down somewhere other than your usual place.","you have eaten a whole meal from the other chair.","to find it uncomfortable and move back before you finish.","warmup"),
(3,"shower","Turn the dial to cold while you are still under it.","thirty seconds of cold have passed and you turned it off, not warm again.","to gasp, panic, and turn it straight back to hot.","warmup"),
(4,"wake","Do the last thing in your routine first, before you can think about it.","the whole routine is done and the order was genuinely reversed.","to get muddled, miss something, and be late.","check"),
(5,"laptop","Take your phone into another room and put it face down.","an hour has passed and you did not go and get it.","to miss something urgent and for it to matter.","check"),
(6,"plate","Open the cupboard and take out the thing you have never opened.","one bite of something you had never eaten is swallowed.","to find it disgusting and to have wasted food.","warmup"),
(7,"charge","Put the album on and sit down before the first track ends.","the album has played to the end without being skipped.","to hate it within two tracks and resent the time.","check"),
(8,"shoes","Leave the headphones on the table, not in your pocket.","ten minutes outside are done with nothing in your ears.","to be bored, and for your own thoughts to be unpleasant company.","music"),
(9,"lights","Find paper and a pen and write the first line, however bad.","one full page is covered in your handwriting.","to have nothing to say and stare at the paper.","check"),
(10,"laptop","Open the first tutorial and do only what it shows in the first minute.","twenty minutes have gone on something your hands have never done.","to be hopeless at it and feel too old to be starting.","record"),
(11,"kettle","Open the fridge and take out three things without deciding anything.","something edible exists and no recipe was consulted.","to ruin it and have to throw it away and start again.","research"),
(12,"lights","Clear two square metres of floor and get into the middle of it.","twenty minutes of a movement your body does not know are behind you.","to look ridiculous and feel your body refuse.","record"),
(13,"lunch","Open the book at page one and read to the bottom of it.","ten pages from a section you never browse are read.","to find it impenetrable and give up on page two.","check"),
(14,"wake","Move the thing out of reach before you want it.","a full day has passed without it and you did not break at the end.","to be irritable, useless, and worse company all day.","warmup"),
(15,"laptop","Get the materials out and put them on the table where you will trip over them.","an object exists that did not exist this morning, however crude.","to make something embarrassing and want to hide it.","record"),
(16,"bag","Pack the one thing you need to do it and leave the house with it.","the usual thing is done, and it was done somewhere you had never done it.","to be unable to concentrate and get nothing done.","warmup"),
(17,"lunch","Open a list of ten words and say the first one out loud.","you can say all ten words without looking.","to forget them within a day and prove you cannot learn languages.","check"),
(18,"lights","Put every screen in a drawer and shut it.","the evening is over and no screen was switched on.","to be bored out of your mind and go to bed at nine.","warmup"),
(19,"wake","Put the thirty minutes in your calendar for all three days, now.","three consecutive days each contain thirty minutes of practice.","to manage one day and quietly drop the other two.","check"),
(20,"laptop","Find out what the repair needs and order the one part.","the thing works, or you know exactly why it does not.","to break it worse and have to pay someone anyway.","research"),
(21,"charge","Set the alarm ninety minutes early and write down what the time is for.","you were awake ninety minutes early and used the time as written.","to lie awake, be exhausted all day, and waste the hour anyway.","today"),
(22,"laptop","Find one class, one date, and book the single session.","you turned up, stayed the whole session, and were visibly the beginner.","to be the worst in the room and for everyone to notice.","alone"),
(23,"laptop","Write the shopping list for the dish before you look up a technique.","the dish was cooked from written instructions. Edible is optional.","to produce something inedible and have wasted the ingredients.","research"),
(24,"lights","Set a timer for two hours and start before you decide what it is.","two hours are gone and nobody has seen it or will.","to make something worthless and feel the two hours were wasted.","record"),
(25,"lights","Pick one movement and do the first set properly.","you stopped at the point your form broke, not before and not after.","to fail early, in front of yourself, well short of anything impressive.","check"),
(26,"wake","Write the one change on a card and put it where the old habit happens.","seven consecutive days contain the change, with no day missed.","to break on day three and prove the whole method does not work.","check"),
(27,"laptop","Name the thing you have avoided. Open one page about how to start it.","you can do the thing, badly, without help.","to find out there was a good reason you avoided it.","research"),
(28,"wake","Cancel or clear the day. That is the whole first move.","a full day has passed with nothing in it that you planned.","to waste the day entirely and feel worse at the end of it.","check"),
(29,"charge","Get the book and read the first page tonight.","the book is finished, cover to cover.","to lose interest at a third of the way in and abandon it.","check"),
(30,"wake","Remove it from the house, or put it somewhere you cannot reach.","seven days have passed without it, with no exceptions made.","to cave by the third day and feel it proves something about you.","warmup"),
(31,"laptop","Find one session happening this week and put your name down.","you were in the room for a full session of something.","to be out of place, underprepared, and clearly the weakest there.","alone"),
(32,"charge","Book the six hours into the week as six separate appointments.","six hours of practice are logged across one week, honestly counted.","to manage two hours and lie to yourself about the rest.","check"),
(33,"known","Say the deadline out loud to one person, with the date in it.","the thing is finished, by the date you said out loud.","to miss the date and have someone know you missed it.","soften"),
(34,"laptop","Find the thing that scares you slightly and book it for a specific day.","you did it, and the slight fear was present the whole time.","to freeze on the day, or to be hurt doing it.","undo"),
(35,"charge","Block eight hours tomorrow and name the one thing in the calendar entry.","eight hours have gone on one thing, start to finish, in one day.","to burn out by hour three and have nothing to show.","check"),
(36,"lunch","Ask one person when they are free to eat. Nothing else yet.","someone else has eaten something you had never made before.","for it to be bad and for them to have to be polite about it.","research"),
(37,"charge","Put the day in the calendar as blocked and silence your phone for it.","a day has passed with no obligation met and nothing scheduled.","to be restless, guilty, and unable to actually rest.","check"),
(38,"lights","Learn the opening four bars or movements only.","you can do the whole sequence through with no prompts.","to forget it halfway and realise you cannot hold anything in your head.","check"),
(39,"charge","Put the three dates in this week now, before you do it once.","the same unfamiliar activity has happened three times inside one week.","to do it once, hate it, and skip the other two.","check"),
(40,"known","Choose the person who will not be kind about it and send one message.","one honest person has seen your work and told you something true.","to be told it is bad in a way you cannot recover from.","friendly","\"I want the real version, not the encouraging one.\""),
(41,"teeth","Put the twenty minutes at the same time every day, starting tonight.","thirty consecutive days each contain twenty minutes.","to miss a few days, lose the chain, and quietly stop.","check"),
(42,"alone_w","Ask one person to watch for five minutes. Do not explain why.","one person has watched you do the thing, live.","to go to pieces with someone watching and be humiliated.","record"),
(43,"laptop","Find the course, check the date, pay the deposit.","two full days of being a beginner are behind you.","to be the least able person there for two whole days.","alone"),
(44,"laptop","Write down last year's best number. That is what you are beating.","this year's number is higher than the one you wrote down.","to fall short of last year and find out you are declining.","check"),
(45,"laptop","Find one place that accepts submissions and open the form.","the work has been sent, sold or submitted somewhere real.","to be rejected, and for the rejection to be the final word.","draft"),
(46,"charge","Delete it, or hand the device to someone else for the week.","seven days have passed with no access to it at all.","to be unbearably bored and to find out you have no interests.","warmup"),
(47,"laptop","Learn the one part someone would actually need from you.","you have used the skill to help another person with a real problem.","to get it wrong and make someone else's situation worse.","research"),
(48,"laptop","Book one ticket, not two.","you have done it alone, start to finish, without arranging company.","to be visibly alone and pitied for it.","alone"),
(49,"laptop","Find the dated event and enter it today, while the date is still far away.","the date arrived and you were prepared enough to turn up.","to be unprepared on the day and to have paid to be humiliated.","undo"),
(50,"charge","Pick the one thing and write down what finished looks like.","one thing is finished. Not improved, not nearly — finished.","to get it to ninety per cent and leave it there like the others.","check"),
]

ROWS += [
(51,"laptop","Find the open mic, jam or tournament and put your name on the list.","you performed or competed in front of people who did not choose to watch you.","to be bad in front of strangers and for it to be visibly awkward.","friendly"),
(52,"laptop","Find one practitioner near you and send one message asking for an hour.","someone better than you has looked closely and said true things.","to be told the work is not worth continuing.","draft","\"Would you look at this and tell me what is wrong with it?\""),
(53,"laptop","Write down the physical thing you had ruled out. Book the first session.","you attempted the thing your body was supposedly not for.","to be physically unable, publicly, and to have the assumption confirmed.","undo"),
(54,"charge","Remove the apps or cancel the subscription tonight.","a month has passed with that form of media entirely absent.","to be out of the loop, bored, and to have missed something that mattered.","warmup"),
(55,"laptop","Find the event with published results and enter it.","your result is recorded somewhere you cannot quietly delete.","to come last, in public, with the number permanently attached to your name.","record"),
(56,"charge","Put the second skill in the calendar without removing the first.","both skills have had real hours this week, neither abandoned.","to lose the first skill while being bad at the second.","check"),
(57,"laptop","Make the thing first. Decide who gets it afterwards.","something you made is in a stranger's hands and your name is not on it.","for them not to want it, and to be embarrassed offering it.","record"),
(58,"wake","Tell the people you live or work with before you start.","a full day has passed without you speaking.","to be unable to manage it and to look foolish for announcing it.","tell"),
(59,"charge","Write seven lines in your notes tonight. One unfamiliar act per day.","seven consecutive days each contain one thing you had never done.","to run out of ideas by day four and let the week collapse.","check"),
(60,"msg","Say yes to the thing you are not qualified for, in writing, today.","the project is delivered, and you were under-qualified when you started.","to be found out mid-project and let someone down badly.","research"),
(61,"laptop","Pay for the six weeks up front so dropping it costs something.","all six weeks were attended, including the ones where you did not want to go.","to drop out around week three and be the person who left.","undo"),
(62,"charge","Put four sessions a week in the calendar for the whole month, now.","four sessions a week for a month, with none quietly dropped.","to miss a week, lose the rhythm, and stop pretending.","check"),
(63,"laptop","Find the room of twenty and ask for a slot.","you spoke or performed in front of more than twenty people.","for your voice to go, your mind to go blank, and the room to see it.","friendly"),
(64,"charge","Define what the one thing is in a single sentence tonight.","a month has gone into one object and the object exists.","to lose interest at week two and have a half-built thing.","check"),
(65,"laptop","Write down the number you are at now, before you start.","the number you wrote down has gone up measurably.","to measure it and find no improvement at all after all that work.","check"),
(66,"msg","Name the 'one day' thing out loud. Do the first part of it that costs something.","the thing you kept saying you would do one day is done.","to do it and find it was never worth all the waiting.","today"),
(67,"laptop","Find the group where you will be the worst and turn up once.","a month has passed in a room where you were the least able person.","to be unwelcome, slow, and a drag on everyone else.","alone"),
(68,"laptop","Name the public end point and put the date in writing.","the date came and you presented, performed or delivered.","to get there unready and fail in front of the people you told.","undo"),
(69,"charge","Write down the routine you have held for five years. Tonight is the last night of it.","a month has passed without the routine you held for five years.","to lose something load-bearing and come apart without it.","check"),
(70,"laptop","Set up where people can see you and start before you are ready.","you worked where people could watch, including the parts that went wrong.","to be watched failing and have no way to hide it.","record"),
(71,"charge","Book all three dates now, across three months.","three public outings happened in three months, however small.","to do the first and find excuses for the other two.","undo"),
(72,"laptop","Find the teacher, class or setting that is not in your language.","you learned the thing in a setting that was not yours.","to understand nothing and waste the money.","research"),
(73,"laptop","Find the qualification, check the date, pay the entry.","you sat the assessment and the result is external and recorded.","to fail it and have the failure be official.","record"),
(74,"charge","Write down the one goal and the date. Then the first week's sessions.","three months of structured training are behind you, pointed at one thing.","to get injured, or bored, and abandon it in month two.","check"),
(75,"charge","Make the first thing tonight and post it before you judge it.","thirty days of work are made and all of it is visible, including the bad.","to post something embarrassing and for people to see it.","record"),
(76,"laptop","Name a price out loud to one person who might pay it.","someone paid you for the skill and received what they paid for.","to charge for something you are not good enough at and be found out.","soften"),
(77,"wake","Remove the essential thing from the house today.","a month has passed without the thing you called non-negotiable.","to discover you genuinely needed it and that the month damaged something.","warmup"),
(78,"laptop","Enter the field where you are clearly outmatched. Pay the entry today.","you turned up and completed it, whatever the placing.","to come last by a humiliating margin.","record"),
(79,"known","Ask one person what their actual problem is. Write it down.","someone else's real problem is solved by something you built.","to build the wrong thing and waste their time as well as yours.","research"),
(80,"known","Find one beginner and offer one hour.","a beginner can now do the first part because of you.","to be exposed as not actually understanding it.","research"),
(81,"laptop","Pick the date, name the session, and tell the first person.","a group turned up and you ran the session end to end.","to lose the room, be asked something you cannot answer, and stall.","friendly"),
(82,"charge","Announce the deadline publicly tonight, with the date.","ninety days ended with the thing delivered on the announced date.","to miss the public deadline and have it be visible.","undo"),
(83,"laptop","Enter the event you had ruled out as being for other people.","you were at the start line of the thing you thought was not for you.","to not finish, and for that to prove you were right to rule it out.","record"),
(84,"laptop","Open your calendar and delete one standing commitment that no longer fits.","your week is rebuilt around what you do now, not what you did.","to dismantle a week that was holding you up and have nothing replace it.","check"),
(85,"laptop","Find one person worth learning from and send one honest message.","you are under someone else's standard, with a schedule you did not set.","to be rejected, or accepted and then found inadequate.","draft"),
(86,"charge","Write down the finish condition tonight, while you still care.","the thing is finished, and it was finished after the interest ran out.","to lose interest and have the unfinished thing sit there as evidence.","check"),
(87,"laptop","Find the strongest field that will accept you and enter it.","you competed at the highest level currently open to you.","to be comprehensively out of your depth and know it publicly.","record"),
(88,"charge","Write the six-month plan on one page. Then book this week.","six months of serious, structured work are behind you.","to plateau at month three and find out you have a ceiling.","check"),
(89,"laptop","Choose the public thing that could genuinely embarrass you. Commit today.","the embarrassing thing happened in public and you are still here.","to be humiliated in a way people remember and bring up.","record"),
(90,"laptop","Find the event with a final, public result and enter it.","the result is public, final, and has your name on it.","to fail visibly, permanently, and on the record.","record"),
(91,"laptop","Write the email, the resignation or the ask. Do not send it yet — write it.","the real professional risk is taken, not deferred again.","for it to go wrong and cost you something you cannot replace.","draft"),
(92,"known","Ask the person whose standards exceed yours for one hour of collaboration.","something exists that neither of you would have made alone.","to be the weak half and for them to regret agreeing.","soften"),
(93,"charge","Write down what a year of this normally looks like. Compress it onto three months.","three months contained a year's worth of effort, honestly counted.","to burn out in week five and lose the rest of the year too.","check"),
(94,"laptop","Find the audience with no connection to you and put the work in front of them.","people who owe you nothing have seen the work and responded.","to be met with indifference, which is worse than criticism.","friendly"),
(95,"charge","Write the thing you are afraid is beyond you on one line. Start the first part.","the thing you called beyond you exists.","to try it, fail, and have the ceiling turn out to be real.","check"),
(96,"laptop","Pick the group and the difficult thing, and set the first date.","a group got through something hard and you led them through it.","for someone to be hurt or lost because you led badly.","soften"),
(97,"charge","Write the practice down as it would look in ten years. Do today's version.","the practice exists in a form you can still be doing in a decade.","to design something you abandon within the year like the others.","check"),
(98,"laptop","Name what you are staking and put it somewhere you cannot take it back.","something you would genuinely miss was staked on your own capability.","to lose it, and for the loss to prove the capability was not real.","undo"),
(99,"wake","Write down what that person's ordinary Tuesday looks like. Live today as it.","thirty consecutive days were lived as the person, not as practice.","to slip back within a week and find the whole thing was a costume.","check"),
(100,"charge","Name the defining routine out loud. Tonight is the last night it runs.","thirty days have passed with the defining routine gone and the new practice in its place.","to lose the routine and find there was no person underneath it.","check"),
]
