# Protocol for the Access ladder. One row per tier:
#   (tier, anchor_id, opener, done, test, drop_id, say)
#
# The openers deserve a note. From roughly tier 40 the directives become trips, and a trip is
# not a thing you can start in two minutes — which is exactly why the old curriculum stalled
# there. So from that point the opener is the *capability* act rather than the journey: put one
# date in, name the place out loud, buy the one ticket you cannot refund. That is the piece
# people actually avoid, and it is the piece that fits in two minutes.
ROWS = [
(1,"shoes","Put your shoes on. That is the whole first move.","you have been back inside with the door shut for one full minute.","to feel watched, and that standing there will feel ridiculous.","phone"),
(2,"corner","Walk to the first lamp post or gate and stop there.","you are back at your own door having turned round at the end of the street.","to be seen going nowhere and feel stupid about it.","phone"),
(3,"shut","Turn left out of your door instead of right.","you have passed your own front door again from the other side.","to find there is nothing to see and that the whole thing is pointless.","phone"),
(4,"shoes","Go out of your own door facing the direction you never face.","you have reached the point where the reversed route rejoins the one you know.","to get disoriented and feel foolish on your own street.","map"),
(5,"corner","Stand at the corner and pick the turning you have never taken.","one block down it is behind you and you have turned for home.","to find it is a dead end, or someone's drive, and be embarrassed.","map"),
(6,"wait","Put your phone in your pocket before you stop walking.","three minutes have passed without you taking your phone out.","to look like you are loitering and for someone to ask what you want.","phone"),
(7,"shoes","Walk to the end of the road and turn whichever way your body goes first.","fifteen minutes have passed with no route decided in advance.","to end up somewhere unpleasant and not know how to get back.","map"),
(8,"shoes","Start a timer for twenty minutes and walk away from your door.","you have reached the twenty-minute mark and know where you are standing.","to run out of pavement, or energy, well before twenty minutes.","map"),
(9,"keys","Leave by a different exit, or turn the wrong way out of it, on purpose.","you have arrived at the usual place by a route you have never used.","to be late, and to resent having made the trip harder.","map"),
(10,"pass","Sit down on the first unfamiliar bench you reach.","you have sat there for ten minutes without getting up early.","to be stared at for sitting still with no reason to be there.","phone"),
(11,"till","Push the door open and get yourself fully inside.","you have been inside long enough to look at one thing properly, and left.","to be approached by staff and have to explain why you came in.","rehearse","\"Just having a look, thanks.\""),
(12,"shoes","Open a map, find the nearest green you cannot name, and start walking.","you are standing on grass you have never stood on.","to find it is small, fenced, or disappointing, and feel the trip was wasted.","phone"),
(13,"corner","Keep going until you reach a sign you have never read, and read it.","you can say the street's name out loud without looking.","to realise you have lived here for years and known nothing.","phone"),
(14,"alarm","Get dressed before you let yourself check the time again.","you were outside and moving for twenty minutes before seven.","to be the only person out, and conspicuous for it.","today"),
(15,"lights","Put your coat on while it is still light enough to leave.","you covered a route you know, in the dark, and came home.","to feel unsafe, and to turn back within a few minutes.","music"),
(16,"shoes","Pick the compass direction you never go and take the first street that heads that way.","you have covered a mile in that one direction before turning back.","to find it is all the same, and that there was no point going.","map"),
(17,"seat","Stay seated when the doors open at your stop.","you made your own way back from one stop past your own.","to misjudge it and end up much further out than you meant.","map"),
(18,"seat","Press the button two stops before you normally would.","you are home by a route you had never used.","to get properly lost and arrive much later than planned.","map"),
(19,"shoes","Look up where your postcode ends before you put your coat on.","you are standing on the boundary, and you know you are.","to find the edge is a dual carriageway, and the whole idea is silly.","phone"),
(20,"shoes","Get to the crossing and look the whole way across it.","you have come back across it under your own power.","to feel exposed halfway across and want to turn round.","music"),
(21,"wait","Get on the first service you have never taken, whichever comes.","you have ridden five stops and got off deliberately.","to end up somewhere you do not want to be, with no way back.","map"),
(22,"shoes","Look up the opening time and write it on your hand.","you have been inside the place locals skip and stayed half an hour.","to feel like a tourist in your own town and be embarrassed.","research"),
(23,"shoes","Put your phone on aeroplane mode before you leave the house.","an hour has passed and you are walking home without having opened a map.","to get lost badly enough that it stops being funny.","map"),
(24,"wait","Buy the ticket to the halfway point before you decide anything else.","you have got off at the halfway stop and stood there for ten minutes.","to arrive somewhere with nothing in it and feel the day was wasted.","research"),
(25,"shoes","Name the district out loud and start moving toward it.","you have spent a full hour there, not in transit to it.","to be obvious, and for people to clock that you are not from there.","phone"),
(26,"laptop","Leave your card at home so the bus stops being an option.","you have covered the whole gap on foot, including the part you always skip.","to find it takes far longer than it should and to regret it.","undo"),
(27,"shoes","Find the highest public point near you and set it as your only destination.","you can see your own area from above and have looked at it for five minutes.","to be turned away, or find it closed, and have made the trip for nothing.","research"),
(28,"shoes","Walk to the water and turn so it is on your left.","you have followed it for a full hour without turning inland.","to get bored, and to find there is nothing to look at.","music"),
(29,"lunch","Walk in and ask for a table for one, out loud.","you have eaten a whole meal there, sitting down, alone.","to be pitied, badly seated, or asked whether someone else is coming.","phone","\"A table for one, please.\""),
(30,"laptop","Choose the slowest option on the departure board, not the next one.","you have arrived where you needed to be by the slowest route available.","to be late, stressed, and to have ruined the day over nothing.","check"),
(31,"shoes","Put the district name in and start the journey before you read anything about it.","you have been there for a full afternoon and your sense of the place has changed.","to find it hostile or boring, and to feel the afternoon was thrown away.","research"),
(32,"wait","Stay on past the last stop you recognise.","you are an hour's walk from the end of the line, on foot.","to be stranded at the edge of the network after dark.","map"),
(33,"shoes","Head for the depots and the yards rather than the centre.","you have spent two hours in the part nobody photographs.","to be obviously out of place, and challenged about why you are there.","record"),
(34,"laptop","Find where to hire or borrow it and make the enquiry today.","you have used it for an hour, badly, in public.","to be visibly incompetent at something you used to do easily.","alone"),
(35,"shoes","Put your phone in your bag, zipped, before you leave the house.","three hours have passed somewhere unfamiliar with no plan and no map.","to run out of things to do within an hour and feel pointless.","map"),
(36,"shoes","Walk through the main door as though you belong there, because you do.","you have sat down inside a public building you had never entered.","to be stopped and asked what you are here for.","rehearse","\"Is it alright if I sit in here for a bit?\""),
(37,"wake","Eat something and fill a bottle before you decide the route.","ten kilometres are behind you in one continuous go.","to have to stop at five and admit you could not do it.","check"),
(38,"shoes","Look up which street is oldest and go to one end of it.","you covered it end to end without cutting any of it out.","to find it is just a road, and that the history is invisible.","research"),
(39,"wake","Fill a bottle and put it by the door tonight.","you have crossed into the next town under your own power.","to run out before the boundary and have to get transport home.","undo"),
(40,"laptop","Open a map, pick a name you cannot picture, and say it out loud.","you have been there, and it is no longer a name you cannot picture.","to find there is nothing there, and that unimaginable just meant dull.","research"),
(41,"laptop","Book the ticket now, before you look the town up.","you have spent four hours there and can state one real thing about it.","to be bored for four hours with nowhere to sit and nothing to see.","research"),
(42,"charge","Put one date in your calendar tonight and block the whole day.","a full day has passed with you outside your own town.","to want to come back by lunchtime and to have wasted the fare.","undo"),
(43,"laptop","Find where that community gathers near you and pick a day.","you have spent an afternoon somewhere your accent is the unusual one.","to be unable to understand anyone and to feel like an intruder.","research"),
(44,"charge","Print or buy one paper map tonight and put your phone in a drawer.","a whole day has passed navigated on signage, paper and memory alone.","to get badly lost and lose hours you could not afford.","map"),
(45,"laptop","Look up the timetable and buy the ticket for a specific sailing.","you have travelled on it and arrived somewhere you had not been.","to find it slow, uncomfortable, and not worth the fare.","undo"),
(46,"wake","Check the tyres and fill two bottles before you look at the route.","you have covered fifty kilometres out and back under your own power.","to break down, or break, twenty kilometres from home.","undo"),
(47,"laptop","Find the nearest piece of real country and put one date against it.","you have stood in terrain that nobody arranged for you.","to find it uncomfortable, cold, and worse than the photographs.","record"),
(48,"laptop","Find one gathering on a date you could actually make, and write the date down.","you have been, bought something, and said thank you to the person who sold it.","to be unwelcome, obviously the outsider, and asked why you came.","alone","\"Can you tell me what this one is?\""),
(49,"charge","Set your alarm and decide nothing else tonight.","a full day has gone by with every destination chosen after you left.","to freeze at the station, pick nothing, and go home.","research"),
(50,"laptop","Work out the three changes on paper and book only the first.","you have arrived somewhere that took three changes to reach.","to miss a connection and be stuck between two places.","undo"),
]

ROWS += [
(51,"charge","Message one person tonight and ask if you can stay, or book the cheapest bed you can find.","you have woken up somewhere that is not your home.","to lie awake all night and want to come home at two in the morning.","undo"),
(52,"wake","Put your shoes by the bed before you sleep.","an hour of moving through an unfamiliar place is behind you, before you ate anything.","to feel lost and exposed walking somewhere you do not know at dawn.","map"),
(53,"laptop","Block two days in your calendar and tell nobody which days they are.","two days have passed away from home with nobody else's plans in them.","to be lonely by the first evening and cut it short.","tell"),
(54,"laptop","Buy the outbound ticket and close the laptop without booking a bed.","you slept somewhere you arranged after you arrived.","to find everything full and end up with nowhere to sleep.","undo"),
(55,"laptop","Find the smallest place with a bed you can reach and book one night.","you have woken up somewhere with fewer people in it than your street.","to be conspicuous in a small place where everyone knows everyone.","research"),
(56,"laptop","Book one night in the biggest city you can reach.","you slept there and covered it the next morning.","to be overwhelmed within an hour and hide in the room.","alone"),
(57,"laptop","Find one overnight service and book the specific departure.","you have woken up somewhere you went to sleep travelling toward.","to get no sleep at all and lose the next day entirely.","undo"),
(58,"wake","Pick one direction out loud and buy only the first ticket.","a full day of travelling in one direction has ended wherever it ended.","to end up somewhere with no bed and no way onward.","research"),
(59,"laptop","Check your passport or papers are valid, today, before anything else.","you have crossed a border you had never crossed.","to be stopped, questioned, or turned back at the line.","research"),
(60,"laptop","Open a map, close your eyes, and put your finger on it. Write down where it landed.","you spent the weekend where chance put you, not where you would have chosen.","to land somewhere awful and spend two days regretting the method.","research"),
(61,"laptop","Book three nights somewhere you cannot name one person in.","three days have passed with no familiar face in them.","to speak to nobody for three days and feel it confirm something.","undo"),
(62,"charge","Pack the bag tonight. Whatever does not fit is not coming.","four days are done and you never opened a second bag.","to need something you left behind and be stuck without it.","undo"),
(63,"laptop","Book the outbound only. Close the tab.","three days passed with the return still unbooked when you set off.","to be unable to get home when you want to, or to pay far more.","undo"),
(64,"laptop","Find the name you cannot say, and book two nights there anyway.","you can pronounce it, and you have slept there twice.","to mispronounce it to someone's face and be corrected or laughed at.","rehearse"),
(65,"laptop","Book it without translating a single sign first.","four days have passed navigating by shape, number and guess.","to get something badly wrong because you could not read a warning.","research"),
(66,"laptop","Book the first night. Leave every other night empty.","five days alone are behind you, with only the first one planned.","to run out of nerve on day two and book a flight home.","undo"),
(67,"laptop","Find the longest single journey you can afford and book it.","one continuous journey of more than eight hours is behind you.","to be trapped, bored and uncomfortable for eight hours with no escape.","undo"),
(68,"laptop","Book two nights in a shared room, not a private one.","you have slept two nights in a room with strangers in it.","to be unable to sleep, and to have nowhere to be alone.","undo"),
(69,"laptop","Request the week off, or block it, before you book anything.","seven consecutive nights have been spent away from your own bed.","to be homesick by day three and count the days down.","undo"),
(70,"laptop","Find out what the cheapest way that far actually costs, and write the number down.","you have been a thousand kilometres from home and come back.","to find it unaffordable, and that the number settles it.","research"),
(71,"laptop","Book a week somewhere you cannot read, and do not install a translator.","a week has passed with every sign a guess.","to make a serious mistake because you could not read something.","research"),
(72,"laptop","Look up what the weather actually is there, then book a week.","a week has passed in air your body has never breathed.","to be ill, uncomfortable, or unable to cope with the climate.","undo"),
(73,"laptop","Book the first night of ten and stop booking.","ten days are behind you and nine of them were decided on the ground.","to waste days deciding and get nowhere at all.","research"),
(74,"laptop","Find where the residents shop, not where visitors eat.","a week has passed using only what the people who live there use.","to be refused, overcharged, or obviously an intruder.","research"),
(75,"laptop","Find a crossing you can reach without a plane and pick the date.","you have crossed a border on foot, by bike or by boat.","to be held at the crossing, or refused for the wrong paperwork.","research"),
(76,"laptop","Put two weeks in the calendar tonight and tell the people who need telling.","fourteen consecutive nights away are behind you.","to be desperate to come home by the end of the first week.","undo"),
(77,"laptop","Open the application form and fill in the first page.","you have been somewhere that required paperwork to enter.","to be refused, and for the refusal to settle the matter for good.","today"),
(78,"charge","Tell the two people who would worry, then leave the charger behind.","three days have passed with nobody able to reach you.","for something to go wrong at home while you are unreachable.","undo"),
(79,"laptop","Book two weeks and do not learn a single phrase first.","two weeks are behind you in a language you cannot hold a conversation in.","to be isolated by the language and to stop trying by week two.","research"),
(80,"laptop","Find the cheapest route that far and write the real cost down.","you have travelled more than five thousand kilometres in one journey.","to be exhausted, jet-lagged, and unable to use the time once there.","research"),
(81,"laptop","Work out what your life costs for three weeks elsewhere and write the number down.","three weeks have passed with your ordinary life running from another place.","to find you cannot work, cannot settle, and lose three weeks of income.","research"),
(82,"laptop","Find one place with a month's let and message whoever holds the keys.","you have had keys to somewhere that was not home for a month.","to be lonely in a flat you are paying for and unable to leave.","undo"),
(83,"laptop","Write down the five things your current routine is made of. All five are about to change.","a month has passed with a routine you built from nothing.","to build nothing, drift for a month, and come back worse.","check"),
(84,"charge","Lay out two weeks of life on the bed. Remove half of it.","two weeks are done and you carried everything you used.","to be dirty, underdressed, or unable to do your work properly.","undo"),
(85,"laptop","Find one posting, course or placement elsewhere and send one message about it.","you have arrived somewhere with an obligation waiting for you.","to be unqualified, out of place, and found out within a week.","draft"),
(86,"laptop","Pick the place where you will never pass as local, and book a month.","thirty days have passed somewhere you were visibly the outsider.","to be stared at daily and never stop feeling watched.","research"),
(87,"laptop","Plan the two weeks overland on paper. No flights on the page.","two weeks of travel are behind you with no air travel in them.","to lose most of the fortnight sitting on trains and buses.","research"),
(88,"laptop","Check your work can run from elsewhere, then block six weeks.","six weeks are behind you, worked through from somewhere else.","to fall behind at work and damage something you cannot repair.","research"),
(89,"laptop","List everything local your week depends on. Every one of them is about to be replaced.","two months have gone by with a doctor, a barber and a shop that are all new.","to be unable to replace any of it, and to feel unmoored for two months.","check"),
(90,"laptop","Book one way. Do not open the return tab.","a month has passed with the return date still genuinely undecided.","to be unable to afford the flight home when you want it.","undo"),
(91,"laptop","Write down the country you would never have picked. That is the one.","two months have passed somewhere that was never on your list.","to have picked badly and be stuck there for two months.","research"),
(92,"laptop","Find out what registering there actually requires, and do the first piece of it today.","three months in, you are registered, you have joined something, and people expect you.","to never get past the paperwork and spend three months as a tourist.","today"),
(93,"laptop","Open the booking. Buy one way only.","you have travelled on a ticket with no return attached.","to regret it the moment the plane lands and have no way back.","undo"),
(94,"laptop","Write the date three months out on a piece of paper and put it somewhere you will see it.","ninety days have passed with no trip home in them.","to need to come back for something and have broken the attempt.","undo"),
(95,"laptop","Name the city. Write down the one thing about it that interested you.","you have work and a bed somewhere you chose out of curiosity alone.","to find curiosity is not enough and to be stranded in a city with no reason.","research"),
(96,"laptop","Find out what releasing or subletting your place would actually take.","a season has passed with no room of yours waiting anywhere.","to come back to nothing and nowhere, and for that to be unrecoverable.","undo"),
(97,"laptop","Book the first two nights. Nothing after that.","three months of continuous movement are behind you with no repeated bed.","to burn out by week six and stop somewhere out of exhaustion.","undo"),
(98,"laptop","Check what a six-month stay legally requires and write the answer down.","six months have passed outside the country you were living in.","to overstay, or be refused, and create a problem you cannot undo.","research"),
(99,"laptop","Pick the place you might actually move to and book a month there first.","you have lived a month in the place before deciding anything about it.","to fall for it on holiday logic and make an expensive mistake.","research"),
(100,"laptop","Open the booking page. One way. Do not look at the return.","you have left with no return date and the decision still genuinely open.","to be unable to come back, or to come back and find nothing waiting.","undo"),
]
